alt_send_esc: false
# window:
  # startup_mode: Maximized
font:
  size: 14.0
  normal:
    family: Comic Code Ligatures
    style: Medium
  bold:
    family: Comic Code Ligatures
    style: Bold
  italic:
    family: Comic Code Ligatures
    style: Italic
